### PR TITLE
Update comment schema

### PR DESCRIPTION
**Pull request by danielpassos**
This PR:

* Remove comments from Meme (type and query)
* Add a new Query (comments by memeid)
* Add Owner relationship from Comment
* Fix Owner relationship on Meme (from Array to a single type)
* Fix responseMapping for all postgres querys
* Probably something else I can't remember right now :bowtie:

### CODE REVIEW

**Comment by wtrocki** [comment]
@danielpassos Changes looks great. I have no specific comment, but it's best to hold off as we do not have this replicated for IOS.

**Comment by wtrocki** [comment]
Going to create ticket to do IOS update.

**Comment by wtrocki** [comment]
let's rebase it later and get that in after demo together with android updates.

**Comment by wtrocki** [comment]
Good stuff. Do we need to udpate proposal?
Let me known when you will be happy for me to check that again

**Comment by danielpassos** [comment]
@wtrocki It's ready for review. I already have changed the Android and going to do the same on iOS.

**Comment by wtrocki** [comment]
Good to be merged. I want to push that to community cluster for wider tests

**Comment by danielpassos** [comment]
@wtrocki Just keep in mind if we update the cluster with it, the released apk will stop to work and there is no reason to have it anymore

**Comment by darahayes** [comment]
@danielpassos no problems with this PR. Just one question. Why remove comments from the meme type?

**Comment by danielpassos** [comment]
@darahayes From the memeolist app perspective

1. I don't know if the comment will be showed (you need to go to the comment screen), so why retrieve the comment with the meme and fire 1 query for each meme?
1. When a new comment is added it will not be displayed in any app without reloading all memes because comments were in the meme type/query

**Comment by darahayes** [comment]
@danielpassos makes perfect sense. LGTM

**Pull request merged**
