### PR TITLE
add health endpoint

### PR DESCRIPTION
**Pull request by pb82**
add health endpoint

### CODE REVIEW

**Comment by aliok** [comment]
Looks good!

@pb82 when I think about this, we need to make sure that application exits gracefully when cannot connect to Postgres (2 cases: config reading, channel listening).
Otherwise, we might still get good health status with this new endpoint even though things are not working.

Could you test that quickly, if interested?

**Comment by pb82** [comment]
@aliok sure, i'll add something like this to the UI too and then to this PR

**Comment by darahayes** [comment]
I would do some small research into how Sequelize handles connection errors just to be sure we don't end up with something like a healthcheck that kills the server because the database was just coming online, or because the connection temporarily dropped.

**Comment by pb82** [comment]
@darahayes @aliok Sequelize suggest to use the `authenticate` method to test the connection: http://docs.sequelizejs.com/manual/installation/getting-started.html#test-the-connection

**Comment by aliok** [comment]
> I would do some small research into how Sequelize handles connection errors just to be sure we don't end up with something like a healthcheck that kills the server because the database was just coming online, or because the connection temporarily dropped.

That's a valid point! I have very little experience how this is handled in other projects. cc @maleck13

**Comment by pb82** [comment]
Closing in favor of new PR

**Pull request closed without merging**
